### ISSUE TITLE
Compile to smali error on kaitlin file.(v1.6)

### ISSUE THREAD

**Issue by guobosheng** [ollide/intellij-java2smali#13]
Plugin Error: java2smali threw an uncaught DexFileNotFoundException.

**Comment by ollide** [comment]
I've just released a new version of the plugin (2.0.1) which delegates the build job better than before and therefore should fix these kind of errors. As this issue is nearly two years old (sorry for not responding before), I'll close this now. Please raise a new one, if you encounter any issues with the current version.

(Duplicate #14 )
