### ISSUE TITLE
.dex does not exist

### ISSUE THREAD

**Issue by lieyunye** [ollide/intellij-java2smali#14]
![5181532849917_ pic_hd](https://user-images.githubusercontent.com/4278280/43364064-7cf8a356-9345-11e8-94fa-6f90bf21d4fe.jpg)
![2018-07-29 3 39 56](https://user-images.githubusercontent.com/4278280/43364074-b2268e62-9345-11e8-998a-ee6d619899cb.png)

**Comment by ollide** [comment]
I've just released a new version of the plugin (2.0.1) which delegates the build job better than before and therefore should fix these kind of errors. As this issue is nearly two years old (sorry for not responding before), I'll close this now. Please raise a new one, if you encounter any issues with the current version.
